// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_achievement_10 = "CgkIjvuZ794QEAIQCQ"; // <GPGSID>
        public const string achievement_achievement_1 = "CgkIjvuZ794QEAIQAA"; // <GPGSID>
        public const string achievement_achievement_2 = "CgkIjvuZ794QEAIQAQ"; // <GPGSID>
        public const string achievement_achievement_3 = "CgkIjvuZ794QEAIQAg"; // <GPGSID>
        public const string achievement_achievement_4 = "CgkIjvuZ794QEAIQAw"; // <GPGSID>
        public const string achievement_achievement_5 = "CgkIjvuZ794QEAIQBA"; // <GPGSID>
        public const string achievement_achievement_6 = "CgkIjvuZ794QEAIQBQ"; // <GPGSID>
        public const string achievement_achievement_7 = "CgkIjvuZ794QEAIQBg"; // <GPGSID>
        public const string achievement_achievement_8 = "CgkIjvuZ794QEAIQBw"; // <GPGSID>
        public const string achievement_achievement_9 = "CgkIjvuZ794QEAIQCA"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIjvuZ794QEAIQCg"; // <GPGSID>

}

